#!/bin/sh

#Input user/pw
. /opt/ftp/variables.txt

#Download Flash Reports
echo "Downloading Flash Reports"
cd /home/homepage/public_html/files/rank/flash/tmpdownload
newflash=`cd /home/homepage/public_html/files/rank/flash/tmpdownload && ls -tr | tail -1`
wget -q -N ftp://ebcogers.la-z-boyaz.com/gers/e1lzbt1/print/FLASH.*  --user=$flash_username --password=$flash_password
chown -R homepage:homepage /home/homepage/public_html/files/rank/flash/tmpdownload/

#Move Latest Flash to intranet site
echo "The Latest Flash is $newflash"
cp $newflash /home/homepage/public_html/files/rank/flash/web/webflash.txt
chown homepage:homepage /home/homepage/public_html/files/rank/flash/web/webflash.txt
